# NeuroVerse Test Solution
# Generated by NeuroVerse AI OS

def top_three_common(numbers):
    from collections import Counter
    if not numbers:
        return []
    counts = Counter(numbers)
    return [value for value, _ in counts.most_common(3)]

# Test
assert top_three_common([1,2,2,3,3,3,4,4,4,4]) == [4,3,2]
assert top_three_common([]) == []
print("All tests passed!")